"""phase_8_recommendation_engine

Revision ID: 3f4678288422
Revises: 986c58d676b5
Create Date: 2026-09-16 10:50:52.403082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4678288422'
down_revision: Union[str, Sequence[str], None] = '986c58d676b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_strategy_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposed_rules', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('backtest_before', sa.JSON(), nullable=True),
    sa.Column('backtest_after', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'REJECTED')", name='ck_pending_strategy_changes_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('backtest_hit_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('backtest_n', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("change_type IN ('AUTO_APPLIED', 'CONFIRMED')", name='ck_strategy_versions_change_type'),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUPERSEDED', 'ROLLED_BACK')", name='ck_strategy_versions_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number', name='uq_strategy_versions_version_number')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('triggered_signals', sa.JSON(), nullable=False),
    sa.Column('risk_blocked', sa.Boolean(), nullable=False),
    sa.Column('risk_block_reason', sa.Text(), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('regime', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('WATCH', 'CONSIDER_INCREASE', 'CONSIDER_DECREASE')", name='ck_recommendations_action'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_signal_snapshots_asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_snapshots')
    op.drop_table('recommendations')
    op.drop_table('strategy_versions')
    op.drop_table('pending_strategy_changes')
    # ### end Alembic commands ###
