"""phase_10_recommendation_outcomes_and_journal

Revision ID: 505c5e07183e
Revises: 3f4678288422
Create Date: 2026-09-17 10:10:38.080420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505c5e07183e'
down_revision: Union[str, Sequence[str], None] = '3f4678288422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('horizon_trading_days', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('outcome_date', sa.Date(), nullable=False),
    sa.Column('from_close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('to_close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('actual_direction', sa.String(length=10), nullable=False),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("actual_direction IN ('BULLISH', 'BEARISH', 'NEUTRAL')", name='ck_recommendation_outcomes_actual_direction'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.add_column('recommendations', sa.Column('as_of_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'as_of_date')
    op.drop_table('recommendation_outcomes')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
