"""phase 5b: dividends table, price valuation columns, asset shares/listing status

Revision ID: 8359a9369503
Revises: e4217df53664
Create Date: 2026-08-31 09:35:48.640755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8359a9369503'
down_revision: Union[str, Sequence[str], None] = 'e4217df53664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ex_dividend_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('cash_dividend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stock_dividend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cash_dividend IS NOT NULL OR stock_dividend IS NOT NULL', name='ck_dividends_has_a_dividend'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'ex_dividend_date', name='uq_dividends_asset_exdate')
    )
    op.add_column('assets', sa.Column('shares_outstanding', sa.Numeric(precision=20, scale=0), nullable=True))
    op.add_column('assets', sa.Column('listing_status', sa.String(length=20), nullable=False, server_default='ACTIVE'))
    # SQLite can't ALTER a table to add a CHECK constraint directly -- needs
    # Alembic's batch mode (copy-and-move strategy).
    with op.batch_alter_table('assets') as batch_op:
        batch_op.create_check_constraint(
            'ck_assets_listing_status', "listing_status IN ('ACTIVE', 'SUSPENDED', 'DELISTED')"
        )
    op.add_column('price_history', sa.Column('adjusted_close', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('price_history', sa.Column('trading_value', sa.Numeric(precision=24, scale=4), nullable=True))
    op.add_column('price_history', sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('price_history', sa.Column('pb_ratio', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('price_history', sa.Column('dividend_yield', sa.Numeric(precision=9, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'dividend_yield')
    op.drop_column('price_history', 'pb_ratio')
    op.drop_column('price_history', 'pe_ratio')
    op.drop_column('price_history', 'trading_value')
    op.drop_column('price_history', 'adjusted_close')
    with op.batch_alter_table('assets') as batch_op:
        batch_op.drop_constraint('ck_assets_listing_status', type_='check')
    op.drop_column('assets', 'listing_status')
    op.drop_column('assets', 'shares_outstanding')
    op.drop_table('dividends')
    # ### end Alembic commands ###
