"""phase 7: composite scoring, INDEX asset type

Revision ID: 986c58d676b5
Revises: b1e14c304976
Create Date: 2026-09-07 10:57:10.309499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986c58d676b5'
down_revision: Union[str, Sequence[str], None] = 'b1e14c304976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # asset_type gains 'INDEX' (for TAIEX, tracked only for regime detection,
    # never a portfolio holding) -- SQLite can't ALTER a CHECK constraint
    # directly, needs Alembic's batch mode (copy-and-move strategy), same
    # pattern already used for ck_assets_listing_status in the Phase 5B
    # migration.
    with op.batch_alter_table('assets') as batch_op:
        batch_op.drop_constraint('ck_assets_asset_type', type_='check')
        batch_op.create_check_constraint(
            'ck_assets_asset_type', "asset_type IN ('STOCK', 'ETF', 'CASH', 'FUND', 'INDEX')"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('growth_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('momentum_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('regime', sa.String(length=10), nullable=True),
    sa.Column('missing_components', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_scores_asset_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###

    with op.batch_alter_table('assets') as batch_op:
        batch_op.drop_constraint('ck_assets_asset_type', type_='check')
        batch_op.create_check_constraint(
            'ck_assets_asset_type', "asset_type IN ('STOCK', 'ETF', 'CASH', 'FUND')"
        )
