"""phase 6: institutional flow, margin trading, monthly revenue

Revision ID: b1e14c304976
Revises: 8359a9369503
Create Date: 2026-08-31 11:16:16.413701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e14c304976'
down_revision: Union[str, Sequence[str], None] = '8359a9369503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('foreign_buy', sa.Integer(), nullable=True),
    sa.Column('foreign_sell', sa.Integer(), nullable=True),
    sa.Column('foreign_net', sa.Integer(), nullable=True),
    sa.Column('investment_trust_buy', sa.Integer(), nullable=True),
    sa.Column('investment_trust_sell', sa.Integer(), nullable=True),
    sa.Column('investment_trust_net', sa.Integer(), nullable=True),
    sa.Column('dealer_buy', sa.Integer(), nullable=True),
    sa.Column('dealer_sell', sa.Integer(), nullable=True),
    sa.Column('dealer_net', sa.Integer(), nullable=True),
    sa.Column('total_net', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_institutional_flows_asset_date')
    )
    op.create_table('margin_trading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('margin_buy', sa.Integer(), nullable=True),
    sa.Column('margin_sell', sa.Integer(), nullable=True),
    sa.Column('margin_cash_repayment', sa.Integer(), nullable=True),
    sa.Column('margin_balance', sa.Integer(), nullable=True),
    sa.Column('short_sale_buy', sa.Integer(), nullable=True),
    sa.Column('short_sale_sell', sa.Integer(), nullable=True),
    sa.Column('short_sale_cash_repayment', sa.Integer(), nullable=True),
    sa.Column('short_sale_balance', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_margin_trading_asset_date')
    )
    op.create_table('monthly_revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('revenue_year', sa.Integer(), nullable=False),
    sa.Column('revenue_month', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revenue_month >= 1 AND revenue_month <= 12', name='ck_monthly_revenue_month_range'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'revenue_year', 'revenue_month', name='uq_monthly_revenue_asset_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_revenue')
    op.drop_table('margin_trading')
    op.drop_table('institutional_flows')
    # ### end Alembic commands ###
