"""initial schema

Revision ID: bb4fb1f98323
Revises: 
Create Date: 2026-08-28 16:44:43.844694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4fb1f98323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('valuation_method', sa.String(length=30), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.CheckConstraint("asset_type IN ('STOCK', 'ETF', 'CASH', 'FUND')", name='ck_assets_asset_type'),
    sa.CheckConstraint("valuation_method IN ('TRANSACTION_BASED', 'MANUAL_MARKET_VALUE')", name='ck_assets_valuation_method'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'date', name='uq_fx_rates_pair_date')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("account_type IN ('BROKERAGE', 'BANK', 'GLOBAL_INVEST', 'CASH')", name='ck_accounts_account_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('debt_ratio', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period', name='uq_fundamentals_asset_period')
    )
    op.create_table('investment_thesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('catalysts', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('key_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('INTACT', 'NEEDS_REVIEW', 'BROKEN')", name='ck_thesis_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.CheckConstraint('close > 0', name='ck_price_history_close_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_price_history_asset_date')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('target_metrics', sa.JSON(), nullable=True),
    sa.Column('entry_consideration', sa.Text(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('WATCHING', 'RESEARCHING', 'CANDIDATE', 'OWNED', 'REJECTED')", name='ck_watchlist_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('BUY', 'SELL', 'DIVIDEND', 'FEE', 'CASH_DEPOSIT', 'CASH_WITHDRAWAL')", name='ck_transactions_type'),
    sa.CheckConstraint('fee >= 0', name='ck_transactions_fee_nonnegative'),
    sa.CheckConstraint('price > 0', name='ck_transactions_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_transactions_quantity_positive'),
    sa.CheckConstraint('tax >= 0', name='ck_transactions_tax_nonnegative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_account_asset', 'transactions', ['account_id', 'asset_id'], unique=False)
    op.create_index('ix_transactions_date', 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_date', table_name='transactions')
    op.drop_index('ix_transactions_account_asset', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('watchlist')
    op.drop_table('price_history')
    op.drop_table('investment_thesis')
    op.drop_table('fundamentals')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('fx_rates')
    op.drop_table('assets')
    # ### end Alembic commands ###
