"""add needs_review to assets

Revision ID: e4217df53664
Revises: bb4fb1f98323
Create Date: 2026-08-28 17:01:42.805924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4217df53664'
down_revision: Union[str, Sequence[str], None] = 'bb4fb1f98323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'needs_review')
    # ### end Alembic commands ###
